import { Container, Header } from "@/shared/component/shared";

export const metadata = {
  title: "Next Pizza | Корзина ",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#f4f1ee]">
      <Container>
      <Header hasSearch={false} hasCart={false} className="border-b-gray-200" />
      {children}
      </Container>
    </main>
  );
}
